# Настройки плагина CombatCooldown (Lumi)

# Общее время в секундах, пока игрок считается в бою
total-seconds: 20

# Текст босс-бара. Используйте %enemy% и %seconds%
text-bar: "§cБой с §f%enemy% §7(| §e%seconds% сек.§7)"

# Сообщение при входе в бой
text-entered: "§6Вы вступили в бой! Не выходите из игры."

# Сообщение по окончании боя
text-quit: "§aВы вышли из боя."

# Сообщение при попытке использовать команды в бою
text-on-command: "§cВы не можете использовать команды во время боя!"


